// Interactive Gift Card CLI (Tx3 off-chain).
//
//   npx tsx src/cli.ts create <token> <lovelace>
//   npx tsx src/cli.ts redeem <redeemAddress>
//
// Resolves/signs/submits through the generated tx3 client against TRP_URL, and
// queries chain state (seed selection, locked-UTxO lookup) through MINIBF_URL.
// Both default to a local `just dev` (trix devnet) — see .env.example.
//
// The locked UTxO carries a void datum, so `redeem` needs the seed + token that
// parameterized the gift card. `create` records those in a small local state
// file (`.gift-cards.json`, gitignored) keyed by redeem address — the CLI analog
// of the canonical Aiken example's browser localStorage. `redeem` reads it back.
//
// NOTE: run `just build` first so the generated client exists at
// .tx3/codegen/ts-client/giftcard/protocol.

import { existsSync, readFileSync, writeFileSync } from "node:fs";

import { Ed25519Signer, Party, PollConfig } from "tx3-sdk";

// Generated by `trix codegen --plugin ts-client` (gitignored).
import { Client } from "../.tx3/codegen/ts-client/giftcard/protocol.js";

import { giftCardFor, loadBlueprint, type Seed } from "./blueprint.js";

const TRP_URL = process.env.TRP_URL ?? "http://localhost:8164";
const MINIBF_URL = (process.env.MINIBF_URL ?? "http://localhost:3164").replace(/\/$/, "");

/** Local state so `redeem` can recover the params `create` used (void datum). */
const STATE_FILE = ".gift-cards.json";
interface GiftRecord {
    seedTx: string;
    seedIx: number;
    token: string;
}
function readState(): Record<string, GiftRecord> {
    return existsSync(STATE_FILE)
        ? (JSON.parse(readFileSync(STATE_FILE, "utf8")) as Record<string, GiftRecord>)
        : {};
}
function recordGift(redeemAddress: string, rec: GiftRecord): void {
    const state = readState();
    state[redeemAddress] = rec;
    writeFileSync(STATE_FILE, JSON.stringify(state, null, 2));
}

function requireEnv(name: string): string {
    const v = process.env[name];
    if (!v) {
        throw new Error(
            `${name} is not set. Copy .env.example to .env.local and fill it in ` +
                `(and start a devnet with \`just dev\` if you haven't).`,
        );
    }
    return v;
}

interface MinibfUtxo {
    tx_hash: string;
    output_index: number;
    amount?: Array<{ unit: string; quantity: string }>;
}

async function utxosAt(address: string): Promise<MinibfUtxo[]> {
    const res = await fetch(`${MINIBF_URL}/addresses/${address}/utxos`);
    if (res.status === 404) return [];
    if (!res.ok) throw new Error(`utxo query failed for ${address}: HTTP ${res.status}`);
    return (await res.json()) as MinibfUtxo[];
}

/** Total lovelace held by a minibf UTxO. */
function lovelaceOf(u: MinibfUtxo): bigint {
    return (u.amount ?? [])
        .filter((a) => a.unit === "lovelace")
        .reduce((sum, a) => sum + BigInt(a.quantity), 0n);
}

// The generated param types declare camelCase keys, but the runtime wants the
// snake_case names from the .tx3 protocol — pass snake_case and cast past the type.
type CreateArgs = Parameters<Client["create"]>[0];
type RedeemArgs = Parameters<Client["redeem"]>[0];

/** Build the owner party + address from the OWNER_* env vars. */
function owner(): { party: Party; address: string } {
    const address = requireEnv("OWNER_ADDRESS");
    const privateKey = requireEnv("OWNER_PRIVATE_KEY");
    return { party: Party.signer(Ed25519Signer.fromHex(address, privateKey)), address };
}

async function create(token: string, lovelace: string): Promise<void> {
    const { party, address } = owner();

    const utxos = await utxosAt(address);
    if (utxos.length === 0) throw new Error(`owner ${address} has no UTxOs to seed a gift card`);
    // Largest UTxO seeds the mint; a smaller one is left for script collateral.
    const seedUtxo = utxos.reduce((a, b) => (lovelaceOf(b) > lovelaceOf(a) ? b : a));
    const seed: Seed = { txHash: seedUtxo.tx_hash, outputIndex: seedUtxo.output_index };

    const gc = giftCardFor(loadBlueprint(), token, seed);

    const client = new Client({ endpoint: TRP_URL }, "local")
        .withOwner(party)
        .withRedeem(Party.address(gc.redeemAddress));

    const submitted = await client
        .create({
            seed: seed.txHash + "#" + seed.outputIndex,
            // A plain number, not a bigint: TRP JSON can't serialize BigInt.
            gift_lovelace: Number(lovelace),
        } as unknown as CreateArgs)
        .env(gc.env)
        .resolve()
        .then((r) => r.sign())
        .then((s) => s.submit());

    await submitted.waitForConfirmed(PollConfig.default());

    // Remember what `redeem` will need (the void datum stores nothing on-chain).
    recordGift(gc.redeemAddress, { seedTx: seed.txHash, seedIx: seed.outputIndex, token });

    console.log("Gift card created.");
    console.log("  token:         ", token, `(${gc.unit})`);
    console.log("  redeem address:", gc.redeemAddress);
    console.log("\nRedeem it with:\n  just redeem", gc.redeemAddress);
}

async function redeem(redeemAddress: string): Promise<void> {
    const { party } = owner();

    const rec = readState()[redeemAddress];
    if (!rec) {
        throw new Error(
            `no local record for ${redeemAddress} in ${STATE_FILE} — it's written by ` +
                `\`create\`, so redeem from the same directory where you created the card.`,
        );
    }
    const seed: Seed = { txHash: rec.seedTx, outputIndex: rec.seedIx };
    const gc = giftCardFor(loadBlueprint(), rec.token, seed);

    const locked = (await utxosAt(redeemAddress))[0];
    if (!locked) throw new Error(`no gift-card UTxO found at ${redeemAddress}`);

    const client = new Client({ endpoint: TRP_URL }, "local")
        .withOwner(party)
        .withRedeem(Party.address(gc.redeemAddress));

    const submitted = await client
        .redeem({ locked: locked.tx_hash + "#" + locked.output_index } as unknown as RedeemArgs)
        .env(gc.env)
        .resolve()
        .then((r) => r.sign())
        .then((s) => s.submit());

    await submitted.waitForConfirmed(PollConfig.default());
    console.log(`Redeemed gift card "${rec.token}" — locked lovelace released to the owner.`);
}

async function main(): Promise<void> {
    const [cmd, ...args] = process.argv.slice(2);
    switch (cmd) {
        case "create":
            if (args.length < 2) throw new Error("usage: cli.ts create <token> <lovelace>");
            await create(args[0], args[1]);
            break;
        case "redeem":
            if (args.length < 1) throw new Error("usage: cli.ts redeem <redeemAddress>");
            await redeem(args[0]);
            break;
        default:
            throw new Error(`unknown command "${cmd ?? ""}" — expected "create" or "redeem"`);
    }
}

main().catch((err) => {
    console.error(err instanceof Error ? err.message : err);
    process.exit(1);
});
