import { afterEach, beforeEach, expect, test } from "vitest";
import { Party } from "tx3-sdk";

import { TestDevnet, DEVNET_POLL } from "../devnet/utils";
import { giftCardFor, loadBlueprint, type GiftCard, type Seed } from "./blueprint";
// Generated by `trix codegen --plugin ts-client` — run `just build`/`just test`.
import { Client } from "../.tx3/codegen/ts-client/giftcard/protocol";

const TOKEN = "hello world";
// A plain number, not a bigint: Int args are JSON-serialized for the TRP call,
// which can't serialize BigInt.
const GIFT_LOVELACE = 5_000_000;

let devnet: TestDevnet;

// A fresh devnet per test: minting/burning the gift-card token mutates chain
// state, so isolation keeps each scenario deterministic.
beforeEach(async () => {
    devnet = await TestDevnet.start({
        // The owner needs a UTxO to seed/fund the mint and a separate one reserved
        // as script collateral (Plutus transactions require it).
        wallets: { owner: [10_000_000_000n, 5_000_000n] },
    });
}, 60_000);
afterEach(() => devnet.stop());

// The tx3 template's runtime arg names are snake_case; the generated param types
// may declare camelCase, so cast past them at the call site (as the reference
// implementation does).
type CreateArgs = Parameters<Client["create"]>[0];
type RedeemArgs = Parameters<Client["redeem"]>[0];

interface Instance {
    client: Client;
    gc: GiftCard;
    seedRef: string;
}

/** Parameterize the gift-card scripts for this run and wire up a client. */
async function configure(): Promise<Instance> {
    const owner = devnet.wallet("owner");
    // Pick the largest UTxO as the mint seed; the smaller one is left for script
    // collateral. minibf returns UTxOs in arbitrary order, so seedUtxo()=utxos[0]
    // would nondeterministically pick the collateral UTxO and fail to fund.
    const utxos = await devnet.utxosOf(owner.address);
    const seedUtxo = utxos.reduce((a, b) => (b.lovelace > a.lovelace ? b : a));
    const seed: Seed = { txHash: seedUtxo.txHash, outputIndex: seedUtxo.outputIndex };

    const gc = giftCardFor(loadBlueprint(), TOKEN, seed);

    const client = new Client({ endpoint: devnet.trpUrl }, "local")
        .withOwner(owner.party)
        .withRedeem(Party.address(gc.redeemAddress));

    return { client, gc, seedRef: seedUtxo.ref };
}

function createTx(inst: Instance) {
    const seed = inst.seedRef;
    const [txHash, ix] = seed.split("#");
    return inst.client
        .create({
            seed,
            gift_lovelace: GIFT_LOVELACE,
            seed_tx: txHash,
            seed_ix: Number(ix),
        } as unknown as CreateArgs)
        .env(inst.gc.env)
        .resolve()
        .then((r) => r.sign())
        .then((s) => s.submit());
}

function redeemTx(inst: Instance, lockedRef: string) {
    return inst.client
        .redeem({ locked: lockedRef } as unknown as RedeemArgs)
        .env(inst.gc.env)
        .resolve()
        .then((r) => r.sign())
        .then((s) => s.submit());
}

/** Await a submitted transaction until the devnet confirms it. */
async function confirm(submitted: ReturnType<typeof createTx>): Promise<void> {
    await (await submitted).waitForConfirmed(DEVNET_POLL);
}

test("creates a gift card locked at the redeem address", async () => {
    const inst = await configure();

    await confirm(createTx(inst));

    const locked = await devnet.utxosOf(inst.gc.redeemAddress);
    expect(locked.length).toBe(1);
}, 60_000);

test("creates and then redeems a gift card", async () => {
    const inst = await configure();

    // 1. Create — mint the token and lock the gift.
    await confirm(createTx(inst));
    const locked = await devnet.utxosOf(inst.gc.redeemAddress);
    expect(locked.length).toBe(1);

    // 2. Redeem — burn the token, release the lovelace; the UTxO is gone.
    await confirm(redeemTx(inst, locked[0].ref));
    expect((await devnet.utxosOf(inst.gc.redeemAddress)).length).toBe(0);
}, 120_000);
